server:
  port: 19091

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**

            - id: hub-service
              uri: lb://hub-service
              predicates:
                - Path=/hubs/**

            - id: company-service
              uri: lb://company-service
              predicates:
                - Path=/companies/**

            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/products/**

            - id: stock-service
              uri: lb://stock-service
              predicates:
                - Path=/stocks/**

            - id: delivery-service
              uri: lb://delivery-service
              predicates:
                - Path=/deliveries/**

            - id: slack-service
              uri: lb://slack-service
              predicates:
                - Path=/slacks/**

            - id: ai-service
              uri: lb://ai-service
              predicates:
                - Path=/ai/**

management:
  endpoints:
    web:
      exposure:
        include: health, refresh