spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}?currentSchema=hub_service
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false