spring:
  profiles:
    active: prod

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:19090/eureka/}

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}
  base-url: "https://dapi.kakao.com"

springdoc:
  servers:
    - url: ${SWAGGER_GATEWAY_URL}
      description: API Gateway URL