services:
  redis:
    image: redis:7.2
    container_name: hublink-redis
    ports:
      - "6379:6379"

  eureka-server:
    image: ${ECR_REGISTRY}/hublink-eureka-server:latest
    container_name: hublink-eureka-server
    ports:
      - "19090:19090"

  api-gateway:
    image: ${ECR_REGISTRY}/hublink-api-gateway:latest
    container_name: hublink-api-gateway
    ports:
      - "19091:19091"
    depends_on:
      - eureka-server
      - config-server

  config-server:
    image: ${ECR_REGISTRY}/hublink-config-server:latest
    container_name: hublink-config-server
    ports:
      - "19092:19092"
    env_file:
      - .env
    depends_on:
      - eureka-server
    volumes:
      - ./config-repo:/config-repo

  user-service:
    image: ${ECR_REGISTRY}/hublink-user-service:latest
    container_name: hublink-user-service
    expose:
      - "19093"
    env_file:
      - .env
    depends_on:
      - eureka-server
      - config-server

  order-service:
    image: ${ECR_REGISTRY}/hublink-order-service:latest
    container_name: hublink-order-service
    expose:
      - "19094"
    env_file:
      - .env
    depends_on:
      - eureka-server
      - config-server

  hub-service:
    image: ${ECR_REGISTRY}/hublink-hub-service:latest
    container_name: hublink-hub-service
    expose:
      - "19095"
    env_file:
      - .env
    depends_on:
      - eureka-server
      - config-server

  company-service:
    image: ${ECR_REGISTRY}/hublink-company-service:latest
    container_name: hublink-company-service
    expose:
      - "19096"
    env_file:
      - .env
    depends_on:
      - eureka-server
      - config-server

  product-service:
    image: ${ECR_REGISTRY}/hublink-product-service:latest
    container_name: hublink-product-service
    expose:
      - "19097"
    env_file:
      - .env
    depends_on:
      - eureka-server
      - config-server

  stock-service:
    image: ${ECR_REGISTRY}/hublink-stock-service:latest
    container_name: hublink-stock-service
    expose:
      - "19098"
    env_file:
      - .env
    depends_on:
      - eureka-server
      - config-server

  delivery-service:
    image: ${ECR_REGISTRY}/hublink-delivery-service:latest
    container_name: hublink-delivery-service
    expose:
      - "19099"
    env_file:
      - .env
    depends_on:
      - redis
      - eureka-server
      - config-server

  slack-service:
    image: ${ECR_REGISTRY}/hublink-slack-service:latest
    container_name: hublink-slack-service
    expose:
      - "19100"
    env_file:
      - .env
    depends_on:
      - redis
      - eureka-server
      - config-server

  ai-service:
    image: ${ECR_REGISTRY}/hublink-ai-service:latest
    container_name: hublink-ai-service
    expose:
      - "19101"
    env_file:
      - .env
    depends_on:
      - redis
      - eureka-server
      - config-server

  zipkin:
    image: openzipkin/zipkin:3.6.1
    container_name: hublink-zipkin
    ports:
      - "9411:9411"

  prometheus:
    image: prom/prometheus:v3.11.3
    container_name: hublink-prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - zipkin

  grafana:
    image: grafana/grafana:13.0.1-security-01
    container_name: hublink-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: