services:
  zipkin:
    image: openzipkin/zipkin:3.6.1
    container_name: hublink-zipkin
    ports:
      - "9411:9411"

  prometheus:
    image: prom/prometheus:v3.11.3
    container_name: hublink-prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - zipkin

  grafana:
    image: grafana/grafana:13.0.1-security-01
    container_name: hublink-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage: