server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/







