global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'hublink-user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'user-service:19093'

  - job_name: 'hublink-order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'order-service:19094'

  - job_name: 'hublink-hub-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'hub-service:19095'

  - job_name: 'hublink-company-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'company-service:19096'

  - job_name: 'hublink-product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'product-service:19097'

  - job_name: 'hublink-stock-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'stock-service:19098'

  - job_name: 'hublink-delivery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'delivery-service:19099'

  - job_name: 'hublink-slack-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'slack-service:19100'

  - job_name: 'hublink-ai-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'ai-service:19101'