server:
  port: 19095

spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health