server:
  port: 19092

spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
          search-locations: file:./config-repo/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health