server:
  port: 19099

spring:
  application:
    name: delivery-service
  config:
    import:
      - "optional:file:.env[.properties]"
      - "optional:file:../.env[.properties]"
      - "optional:configserver:${CONFIG_SERVER_URL:http://localhost:19092}"
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hublink}?currentSchema=delivery_service
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: delivery_service
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true
    fetch-registry: true

swagger:
  gateway-url: ${SWAGGER_GATEWAY_URL:http://localhost:19091}
